# Generated by Django 3.1.4 on 2022-08-06 23:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('modelo', '0003_auto_20220803_1552'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aereolinea',
            fields=[
                ('aereolinea_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=70)),
            ],
        ),
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('pais_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=70)),
            ],
        ),
        migrations.CreateModel(
            name='Ciudad',
            fields=[
                ('ciudad_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=70)),
                ('nombreAereopuerto', models.CharField(max_length=70)),
                ('pais', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modelo.pais')),
            ],
        ),
        migrations.CreateModel(
            name='Boelto',
            fields=[
                ('boleto_id', models.AutoField(primary_key=True, serialize=False)),
                ('num_asiento', models.CharField(max_length=20, unique=True)),
                ('coste', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estado', models.BooleanField(default=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modelo.cliente')),
                ('viaje', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modelo.viaje')),
            ],
        ),
        migrations.CreateModel(
            name='Asiento',
            fields=[
                ('asiento_id', models.AutoField(primary_key=True, serialize=False)),
                ('numero', models.CharField(max_length=20, unique=True)),
                ('categoria', models.CharField(choices=[('ventana', 'Ventana'), ('medio', 'Medio'), ('pasillo', 'Pasillo')], max_length=30)),
                ('estado', models.BooleanField(default=True)),
                ('avion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modelo.avion')),
            ],
        ),
        migrations.AddField(
            model_name='avion',
            name='aereolinea',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='modelo.aereolinea'),
        ),
        migrations.AlterField(
            model_name='viaje',
            name='destino',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modelo.ciudad'),
        ),
    ]
