# Generated by Django 3.1.4 on 2022-08-06 23:07

from django.db import migrations, models
import django.db.models.deletion

class Migration(migrations.Migration):

    dependencies = [
        ('modelo', '0004_auto_20220806_2302'),
    ]

    operations = [
        migrations.CreateModel(
            name='Boelto',
            fields=[
                ('boleto_id', models.AutoField(primary_key=True, serialize=False)),
                ('num_asiento', models.CharField(max_length=20, unique=True)),
                ('coste', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estado', models.BooleanField(default=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modelo.cliente')),
                ('viaje', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modelo.viaje')),
            ],
        ),
        migrations.CreateModel(
            name='Avion',
            fields=[
                ('avion_id', models.AutoField(primary_key=True, serialize=False)),
                ('numero', models.CharField(max_length=20, unique=True)),
                ('capacidad', models.DecimalField(decimal_places=2, max_digits=10)),
                ('puestos_Disponibles', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estado', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Viaje',
            fields=[
                ('viaje_id', models.AutoField(primary_key=True, serialize=False)),
                ('numero', models.CharField(max_length=20, unique=True)),
                ('fechaViaje', models.DateTimeField()),
                ('fechaLlegada', models.DateTimeField()),
                ('destino', models.CharField(max_length=70)),
                ('estado', models.BooleanField(default=True)),
                ('avion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modelo.avion')),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('cliente_id', models.AutoField(primary_key=True, serialize=False)),
                ('cedula', models.CharField(max_length=10, unique=True)),
                ('nombres', models.CharField(max_length=70)),
                ('apellidos', models.CharField(max_length=70)),
                ('genero', models.CharField(choices=[('femenino', 'Femenino'), ('masculino', 'Masculino')], default='masculino', max_length=30)),
                ('correo', models.EmailField(max_length=105)),
                ('celular', models.CharField(max_length=15)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('avion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modelo.avion')),
            ],
        ),
        migrations.AddField(
            model_name='avion',
            name='aereolinea',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='modelo.aereolinea'),
        ),
        migrations.AlterField(
            model_name='viaje',
            name='destino',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modelo.ciudad'),
        ),
        
        migrations.CreateModel(
            name='Asiento',
            fields=[
                ('asiento_id', models.AutoField(primary_key=True, serialize=False)),
                ('numero', models.CharField(max_length=20, unique=True)),
                ('categoria', models.CharField(choices=[('ventana', 'Ventana'), ('medio', 'Medio'), ('pasillo', 'Pasillo')], max_length=30)),
                ('estado', models.BooleanField(default=True)),
                ('avion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modelo.avion')),
            ],
        ),

    ]

