# Generated by Django 3.1.4 on 2022-08-06 23:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('modelo', '0005_auto_20220806_2307'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Boelto',
            new_name='Boleto',
        ),
        migrations.AlterField(
            model_name='cliente',
            name='avion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='modelo.avion'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='celular',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='correo',
            field=models.EmailField(max_length=105, unique=True),
        ),
    ]
