# Generated by Django 3.1.4 on 2022-08-07 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelo', '0006_auto_20220806_2341'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='avion',
        ),
        migrations.AddField(
            model_name='boleto',
            name='categoria_asiento',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='boleto',
            name='coste',
            field=models.DecimalField(decimal_places=2, default=150.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='boleto',
            name='num_asiento',
            field=models.CharField(max_length=20),
        ),
    ]
