# Generated by Django 3.1.4 on 2022-08-07 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelo', '0007_auto_20220807_1828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asiento',
            name='numero',
            field=models.CharField(max_length=20),
        ),
    ]
